---
apiVersion: v1
kind: ConfigMap
metadata:
  name: token-proxy-config
  namespace: ohif-ac
  labels:
    app: token-proxy
data:
  PORT: "3000"
  HOST: "0.0.0.0"
  LOG_LEVEL: "info"
  OAUTH_TOKEN_URL: "https://ciam-radpartners.oktapreview.com/oauth2/ausi5i8tqwLfitWSI1d7/v1/token"
  OAUTH_CLIENT_ID: "0oahv72jg6XGpk4Gd1d7"
  OAUTH_SCOPE: "stream-dicom"
  TOKEN_CACHE_TTL_SEC: "3300"
  TOKEN_EXPIRY_BUFFER_SEC: "300"
  TOKEN_TIMEOUT_MS: "5000"
  VNA_TIMEOUT_MS: "10000"
  VNA_BASE_URL: "https://rp.dev.aws.radpartners.com"
  PROXY_AUTH_MODE: "none"
  FORWARDED_HEADER_ALLOWLIST: "accept,content-type,rp-vna-site-id"
  BODY_SIZE_LIMIT_MB: "10"
  CIRCUIT_BREAKER_TIMEOUT_MS: "30000"
  CIRCUIT_BREAKER_ERROR_THRESHOLD: "50"
  CIRCUIT_BREAKER_RESET_TIMEOUT_MS: "30000"
  TOKEN_RETRY_COUNT: "3"
  TOKEN_RETRY_DELAY_MS: "1000"
  OTEL_SERVICE_NAME: "token-proxy"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: token-proxy
  namespace: ohif-ac
  labels:
    app: token-proxy
    version: v2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: token-proxy
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: token-proxy
        version: v2
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "3000"
        prometheus.io/path: "/metrics"
    spec:
      imagePullSecrets:
      - name: github-registry-secret
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        seccompProfile:
          type: RuntimeDefault
      serviceAccountName: token-proxy
      containers:
      - name: token-proxy
        image: ghcr.io/radpartners/token-proxy:token-proxy-20251223-094754
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
          protocol: TCP
          name: http
        envFrom:
        - configMapRef:
            name: token-proxy-config
        - secretRef:
            name: token-proxy-secret
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi
        securityContext:
          readOnlyRootFilesystem: true
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 15
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /ready
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        volumeMounts:
        - name: tmp
          mountPath: /tmp
      volumes:
      - name: tmp
        emptyDir: {}
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchLabels:
                  app: token-proxy
              topologyKey: kubernetes.io/hostname
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: token-proxy-service
  namespace: ohif-ac
  labels:
    app: token-proxy
spec:
  type: ClusterIP
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
    name: http
  selector:
    app: token-proxy
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: token-proxy
  namespace: ohif-ac
  labels:
    app: token-proxy
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: token-proxy-pdb
  namespace: ohif-ac
  labels:
    app: token-proxy
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: token-proxy
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: token-proxy-hpa
  namespace: ohif-ac
  labels:
    app: token-proxy
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: token-proxy
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Pods
        value: 1
        periodSeconds: 60
    scaleUp:
      stabilizationWindowSeconds: 0
      policies:
      - type: Pods
        value: 2
        periodSeconds: 30
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: token-proxy-network-policy
  namespace: ohif-ac
  labels:
    app: token-proxy
spec:
  podSelector:
    matchLabels:
      app: token-proxy
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: ohif-ac
    - namespaceSelector:
        matchLabels:
          name: istio-system
    ports:
    - protocol: TCP
      port: 3000
  egress:
  # Allow DNS resolution
  - to:
    - namespaceSelector: {}
    ports:
    - protocol: UDP
      port: 53
    - protocol: TCP
      port: 53
  # Allow HTTPS to Okta (token endpoint)
  - to:
    - ipBlock:
        cidr: 0.0.0.0/0
    ports:
    - protocol: TCP
      port: 443
  # Allow HTTP/HTTPS to VNA services (cluster internal)
  - to:
    - namespaceSelector: {}
    ports:
    - protocol: TCP
      port: 80
    - protocol: TCP
      port: 443
    - protocol: TCP
      port: 8080
